- hosts: 10.0.1.44
  tasks:
   - name: Get username
     shell: whoami
     register: theuser

   - name: Get hostname
     shell: hostname
     register: thehost

   - debug: msg="Hasil dari username_custom  {{ username_custom }}, hasil dari password_custom {{ password_custom }}"

   - name: copy file
     copy: src=hello-world.txt dest=/tmp/hello-world.txt
