- hosts: localhost
  collections:
    - cyberark.conjur
  vars:
    ansible_collections_path: /var/lib/awx/.ansible/collections/ansible_collections
  tasks:
   - name: Get username
     shell: whoami
     register: theuser

   - name: Get hostname
     shell: hostname
     register: thehost

   - name: Conjur
     shell: echo {{ lookup('cyberark.conjur.conjur_variable', 'PAM-VAULT/LOB_Conjur01/VI_UNIX_CONJUR/100.0.2.55-administrator-VI_UNIX_SSH/username') }}

   - debug: msg="Hasil dari username_custom  {{ username_custom }}, hasil dari password_custom {{ password_custom }}"

   - name: copy file
     copy: src=hello-world.txt dest=/tmp/hello-world.txt
