---
- hosts: localhost
  tasks:
    #- name: Hapus CONJUR_AUTHN_LOGIN
      #command: echo "CONJUR_AUTHN_LOGIN is $CONJUR_AUTHN_LOGIN"
      #environment:
      #  CONJUR_AUTHN_LOGIN: ""
    #- name: Hapus CONJUR_AUTHN_API_KEY
    #  command: echo "CONJUR_AUTHN_API_KEY is $CONJUR_AUTHN_API_KEY"
    #  environment:
    #    CONJUR_AUTHN_API_KEY: ""
    - name: Get username
      shell: whoami
      register: theuser
    - name: Get hostname
      shell: hostname
      register: thehost
    - name: File path
      shell: printenv
      register: fp
    - name: Conjur
      shell: echo {{ lookup('cyberark.conjur.conjur_variable',
        'PAM-VAULT/LOB_Conjur03/VI_DevOps/100.0.1.77-cityapp-demo-VI_MYSQL/username')
        }}
    #- name: List semua variabel lingkungan
    #  debug:
    #    var: ansible_env
    - name: copy file
      copy: src=hello-world.txt dest=/tmp/hello-world.txt
