- hosts: localhost
  #vars:
  #    ansible_connection: ssh
  #    ansible_host: 100.0.1.77
  #    ansible_user: "administrator"
  #    ansible_password: "Cyberark1"
  tasks:
   - name: Get username
     shell: whoami
     register: theuser

   - name: Get hostname
     shell: hostname
     register: thehost

   - name: File path
     shell: pwd
     register: fp
     
   - name: Conjur
     shell: echo {{ lookup('cyberark.conjur.conjur_variable', 'PAM-VAULT/LOB_Conjur03/VI_DevOps/100.0.1.77-cityapp-demo-VI_MYSQL/username') }}

   - name: copy file
     copy: src=hello-world.txt dest=/tmp/hello-world.txt
